### ISSUE TITLE
Write restart file safely

### ISSUE THREAD

**Issue by ianhinder** [joconnor22/LIFE#2]
Currently, LIFE writes restart files overwriting the previous ones.  If there is a failure during writing the restart file, the original restart file will be lost and the simulation will have to be started from the beginning.  LIFE could instead write the new restart file to a temporary filename, and only when all restart files have been successfully written, rename them over the old ones.

**Comment by joconnor22** [comment]
Hi Ian, that's a good idea, thanks for that. I'll get that done.

**Comment by joconnor22** [comment]
Modified the writeRestart routines to write to temp files first. Tested with no issues.
